//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace MusicalMoments {
    using System;
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class file {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal file() {
        }
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MusicalMoments.file", typeof(file).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        /// <summary>
        ///   查找类似 Love Donation 的本地化字符串。
        /// </summary>
        public static string aifadianResxText {
            get {
                return ResourceManager.GetString("aifadianResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Physical speaker playback synchronization 的本地化字符串。
        /// </summary>
        public static string audioEquipmentPlayResxText {
            get {
                return ResourceManager.GetString("audioEquipmentPlayResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Step 1: Upload a file or drag and drop it here 的本地化字符串。
        /// </summary>
        public static string conversion_Group1ResxText {
            get {
                return ResourceManager.GetString("conversion_Group1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Step 2: Choose the conversion format and convert 的本地化字符串。
        /// </summary>
        public static string conversion_Group2ResxText {
            get {
                return ResourceManager.GetString("conversion_Group2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Hint 的本地化字符串。
        /// </summary>
        public static string conversion_Group3ResxText {
            get {
                return ResourceManager.GetString("conversion_Group3ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string conversion_Label1ResxText {
            get {
                return ResourceManager.GetString("conversion_Label1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Format: 的本地化字符串。
        /// </summary>
        public static string conversion_Label2ResxText {
            get {
                return ResourceManager.GetString("conversion_Label2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Convert 的本地化字符串。
        /// </summary>
        public static string convert_ButtonResxText {
            get {
                return ResourceManager.GetString("convert_ButtonResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Audio Equipment 的本地化字符串。
        /// </summary>
        public static string group_AudioEquipmentResxText {
            get {
                return ResourceManager.GetString("group_AudioEquipmentResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Keys 的本地化字符串。
        /// </summary>
        public static string group_KeyResxText {
            get {
                return ResourceManager.GetString("group_KeyResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Other Settings 的本地化字符串。
        /// </summary>
        public static string group_MiscResxText {
            get {
                return ResourceManager.GetString("group_MiscResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Reference License 的本地化字符串。
        /// </summary>
        public static string info_GroupResxText {
            get {
                return ResourceManager.GetString("info_GroupResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Musical Moments - Music Moments 的本地化字符串。
        /// </summary>
        public static string info_Label1ResxText {
            get {
                return ResourceManager.GetString("info_Label1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Version: 1.1.0-Release+20240228 的本地化字符串。
        /// </summary>
        public static string info_Label2ResxText {
            get {
                return ResourceManager.GetString("info_Label2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 - Major Version: 1
        ///- Minor Version: 1
        ///- Patch Version: 0
        ///- Pre-release Version: Release
        ///- Build Number: 20240228 的本地化字符串。
        /// </summary>
        public static string info_Label3ResxText {
            get {
                return ResourceManager.GetString("info_Label3ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 MM uses the NAudio audio processing library.
        ///NAudio follows the Microsoft Public License (Ms-PL).
        ///Copyright (c) [NAudio]
        ///The full license text can be found at:
        ///https://opensource.org/licenses/MS-PL
        ///Special thanks to NAudio and its contributors. 的本地化字符串。
        /// </summary>
        public static string info_Label5ResxText {
            get {
                return ResourceManager.GetString("info_Label5ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 VB Sound Card Input 的本地化字符串。
        /// </summary>
        public static string label_AudioEquipment1ResxText {
            get {
                return ResourceManager.GetString("label_AudioEquipment1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 VB Sound Card Output 的本地化字符串。
        /// </summary>
        public static string label_AudioEquipment2ResxText {
            get {
                return ResourceManager.GetString("label_AudioEquipment2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Physical Microphone 的本地化字符串。
        /// </summary>
        public static string label_AudioEquipment3ResxText {
            get {
                return ResourceManager.GetString("label_AudioEquipment3ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Physical Speaker 的本地化字符串。
        /// </summary>
        public static string label_AudioEquipment4ResxText {
            get {
                return ResourceManager.GetString("label_AudioEquipment4ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Switch Source Key 的本地化字符串。
        /// </summary>
        public static string label_Key1ResxText {
            get {
                return ResourceManager.GetString("label_Key1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Play Audio Key 的本地化字符串。
        /// </summary>
        public static string label_Key2ResxText {
            get {
                return ResourceManager.GetString("label_Key2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 VB Sound Card Status 的本地化字符串。
        /// </summary>
        public static string label_VBStatusResxText {
            get {
                return ResourceManager.GetString("label_VBStatusResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 The current version only supports conversion from &lt;.ncm&gt; NetEase Cloud Music encrypted files to &lt;.mp3&gt;. More formats will be gradually supported in future versions. 的本地化字符串。
        /// </summary>
        public static string label2ResxText {
            get {
                return ResourceManager.GetString("label2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Simplified Chinese 的本地化字符串。
        /// </summary>
        public static string languageComboBoxResxText {
            get {
                return ResourceManager.GetString("languageComboBoxResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Language: 的本地化字符串。
        /// </summary>
        public static string LanguagelabelResxText {
            get {
                return ResourceManager.GetString("LanguagelabelResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Main 的本地化字符串。
        /// </summary>
        public static string mainGroupBoxResxText {
            get {
                return ResourceManager.GetString("mainGroupBoxResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Open Storage Path 的本地化字符串。
        /// </summary>
        public static string mToAudioData1ResxText {
            get {
                return ResourceManager.GetString("mToAudioData1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Click to Open 的本地化字符串。
        /// </summary>
        public static string mToAudioDataResxText {
            get {
                return ResourceManager.GetString("mToAudioDataResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string PlayAudioResxText {
            get {
                return ResourceManager.GetString("PlayAudioResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string reLoadAudioListsViewResxText {
            get {
                return ResourceManager.GetString("reLoadAudioListsViewResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Redetect 的本地化字符串。
        /// </summary>
        public static string retestVBResxText {
            get {
                return ResourceManager.GetString("retestVBResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Selected: 的本地化字符串。
        /// </summary>
        public static string SelectedAudioLabelResxText {
            get {
                return ResourceManager.GetString("SelectedAudioLabelResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Play hint when switching source 的本地化字符串。
        /// </summary>
        public static string switchStreamTipsResxText {
            get {
                return ResourceManager.GetString("switchStreamTipsResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string tabPage1ResxText {
            get {
                return ResourceManager.GetString("tabPage1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Audio 的本地化字符串。
        /// </summary>
        public static string tabPage2ResxText {
            get {
                return ResourceManager.GetString("tabPage2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string tabPage3ResxText {
            get {
                return ResourceManager.GetString("tabPage3ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Sponsorship 的本地化字符串。
        /// </summary>
        public static string tabPage4ResxText {
            get {
                return ResourceManager.GetString("tabPage4ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string tabPage5ResxText {
            get {
                return ResourceManager.GetString("tabPage5ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Conversion 的本地化字符串。
        /// </summary>
        public static string tabPage6ResxText {
            get {
                return ResourceManager.GetString("tabPage6ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Thank you for your support 的本地化字符串。
        /// </summary>
        public static string thankTipResxText {
            get {
                return ResourceManager.GetString("thankTipResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 First-Time Use Notice 的本地化字符串。
        /// </summary>
        public static string tips_Label1ResxText {
            get {
                return ResourceManager.GetString("tips_Label1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 1. Before first use, install the VB sound card 的本地化字符串。
        /// </summary>
        public static string tips_Label2ResxText {
            get {
                return ResourceManager.GetString("tips_Label2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 2. After installation, bind the corresponding device in settings 的本地化字符串。
        /// </summary>
        public static string tips_Label3ResxText {
            get {
                return ResourceManager.GetString("tips_Label3ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 3. Audio files are located in the root directory [AudioData] 的本地化字符串。
        /// </summary>
        public static string tips_Label4ResxText {
            get {
                return ResourceManager.GetString("tips_Label4ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string ToggleStreamResxText {
            get {
                return ResourceManager.GetString("ToggleStreamResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Go to Bind 的本地化字符串。
        /// </summary>
        public static string toSettingsResxText {
            get {
                return ResourceManager.GetString("toSettingsResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Click to Download 的本地化字符串。
        /// </summary>
        public static string toVBResxText {
            get {
                return ResourceManager.GetString("toVBResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        public static string upData_buttonResxText {
            get {
                return ResourceManager.GetString("upData_buttonResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Volume 的本地化字符串。
        /// </summary>
        public static string volume_GroupResxText {
            get {
                return ResourceManager.GetString("volume_GroupResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Sound Card Mic (100%): 的本地化字符串。
        /// </summary>
        public static string volume_Label1ResxText {
            get {
                return ResourceManager.GetString("volume_Label1ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Physical Mic (100%): 的本地化字符串。
        /// </summary>
        public static string volume_Label2ResxText {
            get {
                return ResourceManager.GetString("volume_Label2ResxText", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Sound Volume (100%): 的本地化字符串。
        /// </summary>
        public static string volume_Label3ResxText {
            get {
                return ResourceManager.GetString("volume_Label3ResxText", resourceCulture);
            }
        }
    }
}
